"""add unique constraints to categories and thresholds

Revision ID: bae128913926
Revises: 20241104_01
Create Date: 2025-11-15 06:10:35.342993

"""

from typing import Sequence, Union

from alembic import op

# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bae128913926"
down_revision: Union[str, None] = "20241104_01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_category_thresholds_user_category', 'category_thresholds', ['user_id', 'category_id'])
    # op.drop_index('ix_notification_events_user_sent', table_name='notification_events')
    # op.create_index(op.f('ix_notification_events_sent_at'), 'notification_events', ['sent_at'], unique=False)
    # op.drop_index('ix_prt_token_hash', table_name='password_reset_tokens')
    # op.drop_index('ix_prt_user_expires', table_name='password_reset_tokens')
    # op.drop_index('ix_prt_user_id', table_name='password_reset_tokens')
    # op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    # op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    # op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # op.drop_index('ix_sessions_refresh_hash', table_name='sessions')
    # op.drop_index('ix_sessions_user_expires', table_name='sessions')
    # op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    # op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=False)
    # op.drop_index('ix_transactions_metadata', table_name='transactions', postgresql_using='gin')
    # op.drop_index('ix_transactions_user_category', table_name='transactions')
    # op.drop_index('ix_transactions_user_occurred', table_name='transactions')
    # op.drop_index('ix_transactions_user_type', table_name='transactions')
    # op.create_index(op.f('ix_transactions_occurred_at'), 'transactions', ['occurred_at'], unique=False)
    # op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###

    op.create_unique_constraint(
        "uq_categories_user_id_name",
        "categories",
        ["user_id", "name"],
    )
    op.create_unique_constraint(
        "uq_category_thresholds_user_category",
        "category_thresholds",
        ["user_id", "category_id"],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('users_email_key', 'users', ['email'])
    # op.drop_index(op.f('ix_transactions_occurred_at'), table_name='transactions')
    # op.create_index('ix_transactions_user_type', 'transactions', ['user_id', 'type', 'occurred_at'], unique=False)
    # op.create_index('ix_transactions_user_occurred', 'transactions', ['user_id', 'occurred_at'], unique=False)
    # op.create_index('ix_transactions_user_category', 'transactions', ['user_id', 'category_id', 'occurred_at'], unique=False)
    # op.create_index('ix_transactions_metadata', 'transactions', ['metadata'], unique=False, postgresql_using='gin')
    # op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    # op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    # op.create_index('ix_sessions_user_expires', 'sessions', ['user_id', 'expires_at'], unique=False)
    # op.create_index('ix_sessions_refresh_hash', 'sessions', ['refresh_token_hash'], unique=False)
    # op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    # op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    # op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    # op.create_index('ix_prt_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    # op.create_index('ix_prt_user_expires', 'password_reset_tokens', ['user_id', 'expires_at'], unique=False)
    # op.create_index('ix_prt_token_hash', 'password_reset_tokens', ['token_hash'], unique=False)
    # op.drop_index(op.f('ix_notification_events_sent_at'), table_name='notification_events')
    # op.create_index('ix_notification_events_user_sent', 'notification_events', ['user_id', 'sent_at'], unique=False)
    # op.drop_constraint('uq_category_thresholds_user_category', 'category_thresholds', type_='unique')
    # ### end Alembic commands ###
    op.drop_constraint(
        "uq_categories_user_id_name",
        "categories",
        type_="unique",
    )
    op.drop_constraint(
        "uq_category_thresholds_user_category",
        "category_thresholds",
        type_="unique",
    )
